language: go

go:
  - 1.9.x

install:
  - go get -u -v $(go list -f '{{join .Imports "\n"}}{{"\n"}}{{join .TestImports "\n"}}' ./... | sort | uniq )
  - mkdir /tmp/sdk
  - curl -o /tmp/sdk.zip "https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.40.zip"
  - unzip -q /tmp/sdk.zip -d /tmp/sdk
  - export PATH="$PATH:/tmp/sdk/go_appengine"
  - export APPENGINE_DEV_APPSERVER=/tmp/sdk/go_appengine/dev_appserver.py

script:
  - go test -v -race -cover github.com/tintinnabulate/vmail/verifier
