// Code generated by "stringer -type ServiceOpportunity enums.go"; DO NOT EDIT.

package main

import "strconv"

const _ServiceOpportunity_name = "OutreachService"

var _ServiceOpportunity_index = [...]uint8{0, 8, 15}

func (i ServiceOpportunity) String() string {
	i -= 1
	if i < 0 || i >= ServiceOpportunity(len(_ServiceOpportunity_index)-1) {
		return "ServiceOpportunity(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ServiceOpportunity_name[_ServiceOpportunity_index[i]:_ServiceOpportunity_index[i+1]]
}
