// Code generated by "stringer -type SpecialNeed enums.go"; DO NOT EDIT.

package main

import "strconv"

const _SpecialNeed_name = "Deaf_or_Hard_of_HearingWheelchair_AccessTranslation_Services"

var _SpecialNeed_index = [...]uint8{0, 23, 40, 60}

func (i SpecialNeed) String() string {
	i -= 1
	if i < 0 || i >= SpecialNeed(len(_SpecialNeed_index)-1) {
		return "SpecialNeed(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SpecialNeed_name[_SpecialNeed_index[i]:_SpecialNeed_index[i+1]]
}
