// Code generated by "stringer -type SpecialNeeds enums.go"; DO NOT EDIT.

package main

import "strconv"

const _SpecialNeeds_name = "Deaf_or_Hard_of_HearingWheelchair_AccessTranslation_Services"

var _SpecialNeeds_index = [...]uint8{0, 23, 40, 60}

func (i SpecialNeeds) String() string {
	i -= 1
	if i < 0 || i >= SpecialNeeds(len(_SpecialNeeds_index)-1) {
		return "SpecialNeeds(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SpecialNeeds_name[_SpecialNeeds_index[i]:_SpecialNeeds_index[i+1]]
}
